### ISSUE TITLE
OLED example?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [natevw/pi-spi#25]
Any examples with an OLED screen?

**Comment by natevw** [comment]
Sorry, nothing available offhand.

Ages ago I added an LCD driver to another node.js framework (https://github.com/ecto/duino/pull/31) — that wasn't even SPI but my general approach would be about the same:

1. find the datasheet for the screen you need to support, or the standards document for the generic protocol
2. design and implement basic "driver" logic that talks with the hardware using lower-level driver libraries like this one/pi-pins/johnny-five/tessel/etc.
3. write test and/or app code that exercises the driver
4. test, troubleshoot, test, troubleshoot, … :-)

Hope this helps, otherwise feel free to re-open (or contact me re. custom work).
